# Generated by Django 2.1 on 2018-08-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='DVD',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Released',
            field=models.DateField(blank=True),
        ),
    ]
