# Generated by Django 2.1 on 2018-08-04 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20180804_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='movie_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Poster',
            field=models.URLField(blank=True),
        ),
    ]
