# Generated by Django 2.1 on 2018-08-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20180804_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Actors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Awards',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Country',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Director',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Genre',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Language',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Metascore',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Plot',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Rated',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Ratings',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Runtime',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Writer',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbID',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbRating',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbVotes',
            field=models.IntegerField(blank=True),
        ),
    ]
